### ISSUE TITLE
Unnecessary requirements

### ISSUE THREAD

**Issue by mmitalidis** [ThanasisMattas/mattflow#6]
https://github.com/ThanasisMattas/mattflow/blob/a265d614a9d6d5ac029f957ab7e909bfe59f68a2/setup.py#L8

Δεν χρειάζεται να συμπεριλάβεις τα requirements των requirements σου. Θα το κάνει αυτόματα το pip.

Αν πχ δε χρησιμοποιείς το cycler και πάψει να είναι requirement των άμεσων requirements σου, τότε εγκαθίσταται χωρίς λόγο.

**Comment by mmitalidis** [comment]
https://github.com/ThanasisMattas/mattflow/blob/a265d614a9d6d5ac029f957ab7e909bfe59f68a2/mattflow/__main__.py#L20

**Comment by ThanasisMattas** [comment]
> https://github.com/ThanasisMattas/mattflow/blob/a265d614a9d6d5ac029f957ab7e909bfe59f68a2/mattflow/__main__.py#L20

? περιττή σειρά?

**Comment by mmitalidis** [comment]
Οχι, οχι. Μια χαρά είναι. Ήθελα να πω ότι το ```pip install mattflow``` είναι αρκετό για το readme
