### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by mmitalidis** [ThanasisMattas/mattflow#8]
Κάποια στιγμή δες

https://realpython.com/python-pep8/
https://www.python.org/dev/peps/pep-0008/

και βάλε στα todo: pylint

**Comment by ThanasisMattas** [comment]
Ωραίος. Οι περιγραφές των συναρτήσεων είναι όπως πρέπει για να γίνεται το linting, αλλά μέχρι εκεί έχω ασχοληθεί.

**Comment by ThanasisMattas** [comment]
Ωραίος. Οι περιγραφές των συναρτήσεων είναι όπως πρέπει για να γίνεται το linting, αλλά μέχρι εκεί έχω ασχοληθεί.
